name: Setup Submodules
description: Sync and update submodules

runs:
  using: composite
  steps:
    - name: Update submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
